spring:
  application:
    name: Spring-Boot-WebFlux-Testing
  data:
    mongodb:
      uri: mongodb+srv://vedha:vedha12%24@dev.qrvz8xo.mongodb.net/mongodb_test?retryWrites=true&w=majority&appName=spring-boot-webflux-testing